import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} scrollbar-thin scrollbar-thumb-[#FF9502] scrollbar-thumb-rounded-md scrollbar-track-rounded-md scroll-m-1 scrollbar-track-white`}
      >
        {children}
      </body>
    </html>
  );
}
